version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - data:/var/opt/mssql

  web:
    container_name: web
    build:
      context: ../src
    ports:
      - "5000:80"
    environment:
      SQLSERVER_HOST: db
      SQLSERVER_SA_PASSWORD: "Your_password123"
    depends_on:
      - db

volumes:
  data: